/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.outlook.ludwen;

import com.gmail.lrchfox3.basedatos.CnnMySql;
import static com.gmail.lrchfox3.utilitarios.Utileria.getFechaActual;
import static com.gmail.lrchfox3.utilitarios.Utileria.getStrFechaActual;
import com.outlook.ludwen.DBObject.CierreDiario;
import com.outlook.ludwen.DBObject.CierreDiarioBC;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LuisR
 */
public class RegistraCierreDiario extends javax.swing.JFrame {

    /**
     * Creates new form CierreDiario
     */
    public RegistraCierreDiario() {
        inicializar();
    }

    private void inicializar() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/outlook/ludwen/Resources/cierrediario.png")));
        CnnMySql.setAccion(CnnMySql.ACCION_INSERT);
        this.dtFechaCierre.setVisible(false);
        this.dtFechaCierre.setDate(getFechaActual());
        this.lblFechaCierre.setText(getStrFechaActual(getFechaActual(), "dd/MM/yyyy"));
        ObtenerCierre(getStrFechaActual(getFechaActual(), "ddMMyyyy"));
        
        this.txtFacturado.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popCaja = new javax.swing.JPopupMenu();
        mnuLimpiar = new javax.swing.JMenuItem();
        pnlCaja = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblCantidadBilletes = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl500 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl100 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl50 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl20 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl10 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblCajaInicial = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        txtCantidad500 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad100 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad50 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad20 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad10 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad5 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad2 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad1 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtMontoMonedas = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblMontoTotalCaja = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        lblMonto50 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto500 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto100 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto10 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto20 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblApertura = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblTotalCaja = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonedas = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblApertura1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblCajaApertura = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        jPanelConTitulo1 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblFacturado = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        jTextoScrollBase1 = new com.gmail.lrchfox3.controles.textos.JTextoScrollBase();
        txtFacturado = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        jPanelConTitulo2 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblPOS1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtPOS1 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblJustificacion = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtPOS2 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblPOS2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        btnAceptar = new com.gmail.lrchfox3.controles.botones.JBotonAceptar();
        txtDiferencia = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        lblDiferencia = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJustificacion = new javax.swing.JTextPane();
        lbl505 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtDeposito = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblCaja = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblCajaFinal = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        txtMontoJustificacion = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        jPanelConTitulo3 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblAperturaAnterior = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblFacturadoAnterior = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblCantidadBilletes3 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblCantidadBilletes4 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblDiferenciaAnterior = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtPOS4 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtPOS5 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblDepositoAnterior = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJustificacionAnterior = new com.gmail.lrchfox3.controles.textos.JComentarioBase();
        lblCantidadBilletes5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jPanelConTitulo4 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblFechaCierre = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        btnEditarFechaCierre = new com.gmail.lrchfox3.controles.botones.paint.JBotonLapiz();
        dtFechaCierre = new com.gmail.lrchfox3.utilitarios.calendario.JDateChooser();
        lblFecha = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();

        mnuLimpiar.setText("Limpiar");
        mnuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLimpiarActionPerformed(evt);
            }
        });
        popCaja.add(mnuLimpiar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cierre Diario");
        setResizable(false);
        setState(1);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlCaja.setComponentPopupMenu(popCaja);
        pnlCaja.setTitulo("Caja");

        lblCantidadBilletes.setText("Cantidad de Billetes:");
        lblCantidadBilletes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl500.setLabelFor(txtCantidad500);
        lbl500.setText("500 x");
        lbl500.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl100.setLabelFor(txtCantidad100);
        lbl100.setText("100 x");
        lbl100.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl50.setLabelFor(txtCantidad50);
        lbl50.setText("50 x");
        lbl50.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl20.setLabelFor(txtCantidad20);
        lbl20.setText("20 x");
        lbl20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl10.setLabelFor(txtCantidad10);
        lbl10.setText("10 x");
        lbl10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl5.setLabelFor(txtCantidad5);
        lbl5.setText("5 x");
        lbl5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl2.setLabelFor(txtCantidad2);
        lbl2.setText("2 x");
        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl1.setLabelFor(txtCantidad1);
        lbl1.setText("1 x");
        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblCajaInicial.setText("Lps");
        lblCajaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCajaInicialMouseClicked(evt);
            }
        });

        txtCantidad500.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad500.setComas(true);
        txtCantidad500.setExpresionRegular("\\d*");
        txtCantidad500.setFormato(1);
        txtCantidad500.setMaxCaracteres(4);
        txtCantidad500.setNextFocusableComponent(txtCantidad100);
        txtCantidad500.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad500FocusLost(evt);
            }
        });
        txtCantidad500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad500KeyReleased(evt);
            }
        });

        txtCantidad100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad100.setComas(true);
        txtCantidad100.setFormato(1);
        txtCantidad100.setMaxCaracteres(4);
        txtCantidad100.setNextFocusableComponent(txtCantidad50);
        txtCantidad100.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad100FocusLost(evt);
            }
        });
        txtCantidad100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad100KeyReleased(evt);
            }
        });

        txtCantidad50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad50.setComas(true);
        txtCantidad50.setFormato(1);
        txtCantidad50.setMaxCaracteres(4);
        txtCantidad50.setNextFocusableComponent(txtCantidad20);
        txtCantidad50.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad50FocusLost(evt);
            }
        });
        txtCantidad50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad50KeyReleased(evt);
            }
        });

        txtCantidad20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad20.setComas(true);
        txtCantidad20.setFormato(1);
        txtCantidad20.setMaxCaracteres(4);
        txtCantidad20.setNextFocusableComponent(txtCantidad10);
        txtCantidad20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad20FocusLost(evt);
            }
        });
        txtCantidad20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad20KeyReleased(evt);
            }
        });

        txtCantidad10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad10.setComas(true);
        txtCantidad10.setFormato(1);
        txtCantidad10.setMaxCaracteres(4);
        txtCantidad10.setNextFocusableComponent(txtCantidad5);
        txtCantidad10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad10FocusLost(evt);
            }
        });
        txtCantidad10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad10KeyReleased(evt);
            }
        });

        txtCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad5.setComas(true);
        txtCantidad5.setFormato(1);
        txtCantidad5.setMaxCaracteres(4);
        txtCantidad5.setNextFocusableComponent(txtCantidad2);
        txtCantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad5FocusLost(evt);
            }
        });
        txtCantidad5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad5KeyReleased(evt);
            }
        });

        txtCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad2.setComas(true);
        txtCantidad2.setFormato(1);
        txtCantidad2.setMaxCaracteres(4);
        txtCantidad2.setNextFocusableComponent(txtCantidad1);
        txtCantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad2FocusLost(evt);
            }
        });
        txtCantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad2KeyReleased(evt);
            }
        });

        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad1.setComas(true);
        txtCantidad1.setFormato(1);
        txtCantidad1.setMaxCaracteres(4);
        txtCantidad1.setNextFocusableComponent(txtMontoMonedas);
        txtCantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad1FocusLost(evt);
            }
        });
        txtCantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad1KeyReleased(evt);
            }
        });

        txtMontoMonedas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoMonedas.setComas(true);
        txtMontoMonedas.setFormato(2);
        txtMontoMonedas.setNextFocusableComponent(txtPOS1);
        txtMontoMonedas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMontoMonedasFocusLost(evt);
            }
        });
        txtMontoMonedas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoMonedasKeyReleased(evt);
            }
        });

        lblMontoTotalCaja.setText("Lps");

        lblMonto50.setText("=");
        lblMonto50.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto500.setText("= ");
        lblMonto500.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto5.setText("=");
        lblMonto5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto100.setText("=");
        lblMonto100.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto10.setText("=");
        lblMonto10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto2.setText("=");
        lblMonto2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto20.setText("=");
        lblMonto20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto1.setText("=");
        lblMonto1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblApertura.setText("Apertura");
        lblApertura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblTotalCaja.setText("Total");
        lblTotalCaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMonedas.setLabelFor(txtMontoMonedas);
        lblMonedas.setText("Monedas");
        lblMonedas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblApertura1.setText("Total Caja - Caja Apertura");
        lblApertura1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblCajaApertura.setText("Lps");

        javax.swing.GroupLayout pnlCajaLayout = new javax.swing.GroupLayout(pnlCaja);
        pnlCaja.setLayout(pnlCajaLayout);
        pnlCajaLayout.setHorizontalGroup(
            pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addComponent(txtCantidad20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCantidadBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonto500, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMontoTotalCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(txtCantidad100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMonto100, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCajaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblApertura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCajaApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCajaLayout.setVerticalGroup(
            pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidad100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMonto100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMontoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblMontoTotalCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajaApertura, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(lblApertura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelConTitulo1.setComponentPopupMenu(popCaja);
        jPanelConTitulo1.setTitulo("Facturado");

        lblFacturado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacturado.setText("Lps");

        txtFacturado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFacturado.setComas(false);
        txtFacturado.setNextFocusableComponent(btnEditarFechaCierre);
        txtFacturado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFacturadoFocusLost(evt);
            }
        });
        txtFacturado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFacturadoKeyReleased(evt);
            }
        });
        jTextoScrollBase1.setViewportView(txtFacturado);

        javax.swing.GroupLayout jPanelConTitulo1Layout = new javax.swing.GroupLayout(jPanelConTitulo1);
        jPanelConTitulo1.setLayout(jPanelConTitulo1Layout);
        jPanelConTitulo1Layout.setHorizontalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextoScrollBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFacturado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelConTitulo1Layout.setVerticalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                .addComponent(jTextoScrollBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFacturado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelConTitulo2.setComponentPopupMenu(popCaja);
        jPanelConTitulo2.setTitulo("Cierre");

        lblPOS1.setLabelFor(txtCantidad500);
        lblPOS1.setText("Continental");
        lblPOS1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtPOS1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPOS1.setComas(true);
        txtPOS1.setFormato(2);
        txtPOS1.setNextFocusableComponent(txtPOS2);

        lblJustificacion.setLabelFor(txtCantidad500);
        lblJustificacion.setText("Justificación");
        lblJustificacion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtPOS2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPOS2.setComas(true);
        txtPOS2.setFormato(2);
        txtPOS2.setNextFocusableComponent(txtMontoJustificacion);
        txtPOS2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPOS2FocusLost(evt);
            }
        });

        lblPOS2.setLabelFor(txtCantidad500);
        lblPOS2.setText("Atlantida");
        lblPOS2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnAceptar.setNextFocusableComponent(txtFacturado);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        txtDiferencia.setEditable(false);
        txtDiferencia.setMinimumSize(new java.awt.Dimension(4, 19));

        lblDiferencia.setLabelFor(txtCantidad500);
        lblDiferencia.setText("Diferencia");
        lblDiferencia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtJustificacion.setNextFocusableComponent(txtDeposito);
        jScrollPane1.setViewportView(txtJustificacion);

        lbl505.setLabelFor(txtCantidad500);
        lbl505.setText("Deposito Banco");
        lbl505.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtDeposito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDeposito.setComas(true);
        txtDeposito.setFormato(2);
        txtDeposito.setNextFocusableComponent(btnAceptar);
        txtDeposito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepositoFocusLost(evt);
            }
        });

        lblCaja.setText("Caja");
        lblCaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblCajaFinal.setText("Lps");

        txtMontoJustificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoJustificacion.setComas(true);
        txtMontoJustificacion.setFormato(2);
        txtMontoJustificacion.setNextFocusableComponent(txtJustificacion);

        javax.swing.GroupLayout jPanelConTitulo2Layout = new javax.swing.GroupLayout(jPanelConTitulo2);
        jPanelConTitulo2.setLayout(jPanelConTitulo2Layout);
        jPanelConTitulo2Layout.setHorizontalGroup(
            jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConTitulo2Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJustificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPOS1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtMontoJustificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPOS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPOS2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtDiferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addComponent(lbl505, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addComponent(lblCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCajaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConTitulo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanelConTitulo2Layout.setVerticalGroup(
            jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJustificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoJustificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPOS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPOS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl505, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCajaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelConTitulo3.setTitulo("Cierre día Anterior");

        lblAperturaAnterior.setText("Apertura: ");
        lblAperturaAnterior.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblFacturadoAnterior.setText("Facturado:");
        lblFacturadoAnterior.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblCantidadBilletes3.setText("Diferencia:");
        lblCantidadBilletes3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblCantidadBilletes4.setText("Deposito:");
        lblCantidadBilletes4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblDiferenciaAnterior.setEditable(false);
        lblDiferenciaAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblDiferenciaAnterior.setComas(true);
        lblDiferenciaAnterior.setFormato(2);
        lblDiferenciaAnterior.setNextFocusableComponent(txtMontoJustificacion);
        lblDiferenciaAnterior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDiferenciaAnteriorFocusLost(evt);
            }
        });
        lblDiferenciaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDiferenciaAnteriorActionPerformed(evt);
            }
        });

        txtPOS4.setEditable(false);
        txtPOS4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPOS4.setComas(true);
        txtPOS4.setFormato(2);
        txtPOS4.setNextFocusableComponent(txtMontoJustificacion);
        txtPOS4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPOS4FocusLost(evt);
            }
        });

        txtPOS5.setEditable(false);
        txtPOS5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPOS5.setComas(true);
        txtPOS5.setFormato(2);
        txtPOS5.setNextFocusableComponent(txtMontoJustificacion);
        txtPOS5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPOS5FocusLost(evt);
            }
        });

        lblDepositoAnterior.setEditable(false);
        lblDepositoAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblDepositoAnterior.setComas(true);
        lblDepositoAnterior.setFormato(2);
        lblDepositoAnterior.setNextFocusableComponent(txtMontoJustificacion);
        lblDepositoAnterior.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDepositoAnteriorFocusLost(evt);
            }
        });
        lblDepositoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDepositoAnteriorActionPerformed(evt);
            }
        });

        txtJustificacionAnterior.setEditable(false);
        txtJustificacionAnterior.setColumns(20);
        txtJustificacionAnterior.setRows(5);
        jScrollPane2.setViewportView(txtJustificacionAnterior);

        lblCantidadBilletes5.setText("Justificacion:");
        lblCantidadBilletes5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelConTitulo3Layout = new javax.swing.GroupLayout(jPanelConTitulo3);
        jPanelConTitulo3.setLayout(jPanelConTitulo3Layout);
        jPanelConTitulo3Layout.setHorizontalGroup(
            jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                        .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblCantidadBilletes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAperturaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFacturadoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCantidadBilletes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPOS5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(lblDepositoAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPOS4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiferenciaAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCantidadBilletes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanelConTitulo3Layout.setVerticalGroup(
            jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAperturaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPOS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacturadoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPOS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBilletes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepositoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadBilletes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiferenciaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCantidadBilletes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelConTitulo4.setTitulo("Fecha Cierre");

        lblFechaCierre.setText("25/02/2015");

        btnEditarFechaCierre.setToolTipText("Lápiz");
        btnEditarFechaCierre.setNextFocusableComponent(txtCantidad500);
        btnEditarFechaCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFechaCierreActionPerformed(evt);
            }
        });

        dtFechaCierre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setLabelFor(lblFechaCierre);
        lblFecha.setText("Fecha");
        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelConTitulo4Layout = new javax.swing.GroupLayout(jPanelConTitulo4);
        jPanelConTitulo4.setLayout(jPanelConTitulo4Layout);
        jPanelConTitulo4Layout.setHorizontalGroup(
            jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConTitulo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelConTitulo4Layout.setVerticalGroup(
            jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConTitulo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dtFechaCierre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarFechaCierre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelConTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelConTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(jPanelConTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(jPanelConTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanelConTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelConTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelConTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelConTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(724, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarFechaCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFechaCierreActionPerformed
        HabilitarControles(false);
        if (this.dtFechaCierre.isVisible()) {
            SimpleDateFormat sdfDate = new SimpleDateFormat("dd/MM/yyyy");
            this.lblFechaCierre.setText(sdfDate.format(this.dtFechaCierre.getDate()));
            this.lblFechaCierre.setVisible(true);
            this.dtFechaCierre.setVisible(false);
            limpiar();
            sdfDate.applyPattern("ddMMyyyy");
            ObtenerCierre(sdfDate.format(this.dtFechaCierre.getDate()));
            HabilitarControles(true);
        } else {
            this.lblFechaCierre.setVisible(false);
            this.dtFechaCierre.setVisible(true);
        }

    }//GEN-LAST:event_btnEditarFechaCierreActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtFacturado.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtCantidad500FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad500FocusLost
           this.lblMonto500.setText("=" );
        if (this.txtCantidad500.getTextoSinFormato().length() > 0) {
            double cantidad = 500 * Double.parseDouble(this.txtCantidad500.getTextoSinFormato());
            this.lblMonto500.setText("= Lps " + df2.format(cantidad));
        }        
        totalCaja();
    }//GEN-LAST:event_txtCantidad500FocusLost

    private void txtCantidad100FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad100FocusLost
        this.lblMonto100.setText("=");
        if (this.txtCantidad100.getTextoSinFormato().length() > 0) {
            double cantidad = 100 * Double.parseDouble(this.txtCantidad100.getTextoSinFormato());
            this.lblMonto100.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad100FocusLost

    private void txtCantidad50FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad50FocusLost
        this.lblMonto50.setText("=");
        if (this.txtCantidad50.getTextoSinFormato().length() > 0) {
            double cantidad = 50 * Double.parseDouble(this.txtCantidad50.getTextoSinFormato());
            this.lblMonto50.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad50FocusLost

    private void txtCantidad20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad20FocusLost
        this.lblMonto20.setText("=");
        if (this.txtCantidad20.getTextoSinFormato().length() > 0) {
            double cantidad = 20 * Double.parseDouble(this.txtCantidad20.getTextoSinFormato());
            this.lblMonto20.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad20FocusLost

    private void txtCantidad10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad10FocusLost
        this.lblMonto10.setText("=");
        if (this.txtCantidad10.getTextoSinFormato().length() > 0) {
            double cantidad = 10 * Double.parseDouble(this.txtCantidad10.getTextoSinFormato());
            this.lblMonto10.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad10FocusLost

    private void txtCantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad5FocusLost
        this.lblMonto5.setText("=");
        if (this.txtCantidad5.getTextoSinFormato().length() > 0) {
            double cantidad = 5 * Double.parseDouble(this.txtCantidad5.getTextoSinFormato());
            this.lblMonto5.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad5FocusLost

    private void txtCantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad2FocusLost
        this.lblMonto2.setText("=");
        if (this.txtCantidad2.getTextoSinFormato().length() > 0) {
            double cantidad = 2 * Double.parseDouble(this.txtCantidad2.getTextoSinFormato());
            this.lblMonto2.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad2FocusLost

    private void txtCantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad1FocusLost
        this.lblMonto1.setText("=");
        if (this.txtCantidad1.getTextoSinFormato().length() > 0) {
            double cantidad = 1 * Double.parseDouble(this.txtCantidad1.getTextoSinFormato());
            this.lblMonto1.setText("= Lps " + df2.format(cantidad));
        }
        totalCaja();
    }//GEN-LAST:event_txtCantidad1FocusLost

    private void txtCantidad500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad500KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad100.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad500KeyReleased

    private void txtCantidad100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad100KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad50.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad100KeyReleased

    private void txtCantidad50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad50KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad20.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad50KeyReleased

    private void txtCantidad20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad20KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad10.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad20KeyReleased

    private void txtCantidad10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad10KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad5.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad10KeyReleased

    private void txtCantidad5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad5KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad2.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad5KeyReleased

    private void txtCantidad2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad1.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad2KeyReleased

    private void txtCantidad1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtMontoMonedas.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad1KeyReleased

    private void mnuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_mnuLimpiarActionPerformed


    private void txtPOS2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPOS2FocusLost
        diferencia();
    }//GEN-LAST:event_txtPOS2FocusLost

    private void txtDepositoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepositoFocusLost
        cajaFinal();
    }//GEN-LAST:event_txtDepositoFocusLost

    private void txtFacturadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacturadoFocusLost
        calcularFacturado();

    }//GEN-LAST:event_txtFacturadoFocusLost

    private void txtMontoMonedasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMontoMonedasFocusLost
        totalCaja();
    }//GEN-LAST:event_txtMontoMonedasFocusLost

    private void txtMontoMonedasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoMonedasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtFacturado.requestFocus();
        }
    }//GEN-LAST:event_txtMontoMonedasKeyReleased

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        try {
            guardar();
            JOptionPane.showMessageDialog(this, "Se guaradon los cambios", "Cierre Diario", 1);
        } catch (ParseException | SQLException | IllegalArgumentException | IllegalAccessException ex) {
            Logger.getLogger(RegistraCierreDiario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void lblCajaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCajaInicialMouseClicked
        if (evt.getClickCount() > 1) {
            String respuesta = JOptionPane.showInputDialog(this, "Ingrese Caja Inicial", "Cierre Diario", JOptionPane.QUESTION_MESSAGE);
            lblCajaInicial.setText("Lps " + df2.format(Double.valueOf(respuesta)));
        }
    }//GEN-LAST:event_lblCajaInicialMouseClicked

    private void txtFacturadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacturadoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad500.requestFocus();
        }
    }//GEN-LAST:event_txtFacturadoKeyReleased

    private void lblDiferenciaAnteriorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDiferenciaAnteriorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDiferenciaAnteriorFocusLost

    private void txtPOS4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPOS4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOS4FocusLost

    private void txtPOS5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPOS5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOS5FocusLost

    private void lblDiferenciaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDiferenciaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDiferenciaAnteriorActionPerformed

    private void lblDepositoAnteriorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDepositoAnteriorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDepositoAnteriorFocusLost

    private void lblDepositoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDepositoAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDepositoAnteriorActionPerformed

    private void calcularFacturado() {
        int pos = 0;
        try {
            StringTokenizer tokens = new StringTokenizer(txtFacturado.getText(), "+");
            Double fact = 0.0;
            while (tokens.hasMoreTokens()) {
                String token = tokens.nextToken();
                pos = pos + token.length() + 1;
                if (!token.isEmpty()) {
                    Double val = new Double(token);
                    fact = fact + val;
                }
            }
            facturado = fact;
            lblFacturado.setText("Lps " + df2.format(fact));

        } catch (Exception e) {
            txtFacturado.setCaretPosition(pos - 1);
            txtFacturado.setForeground(Color.red);
            txtFacturado.requestFocus();
        }
    }

    private void limpiar() {
        this.txtCantidad500.setText("");
        this.txtCantidad100.setText("");
        this.txtCantidad50.setText("");
        this.txtCantidad20.setText("");
        this.txtCantidad10.setText("");
        this.txtCantidad5.setText("");
        this.txtCantidad2.setText("");
        this.txtCantidad1.setText("");
        this.txtMontoMonedas.setText("");
        this.lblMonto500.setText("=");
        this.lblMonto100.setText("=");
        this.lblMonto50.setText("=");
        this.lblMonto20.setText("=");
        this.lblMonto10.setText("=");
        this.lblMonto5.setText("=");
        this.lblMonto2.setText("=");
        this.lblMonto1.setText("=");
        this.lblMontoTotalCaja.setText("Lps");
        this.lblCajaApertura.setText("Lps");
        this.txtFacturado.setText("");
        this.txtPOS1.setText("");
        this.txtPOS2.setText("");
        this.txtMontoJustificacion.setText("");
        this.txtJustificacion.setText("");
        this.txtDeposito.setText("");
        this.lblCajaFinal.setText("Lps");
        this.lblFacturado.setText("");
        this.txtDiferencia.setText("");
        this.txtFacturado.requestFocus();
    }

    private void HabilitarControles(boolean value) {
        this.txtCantidad500.setEnabled(value);
        this.txtCantidad100.setEnabled(value);
        this.txtCantidad50.setEnabled(value);
        this.txtCantidad20.setEnabled(value);
        this.txtCantidad10.setEnabled(value);
        this.txtCantidad5.setEnabled(value);
        this.txtCantidad2.setEnabled(value);
        this.txtCantidad1.setEnabled(value);
        this.txtMontoMonedas.setEnabled(value);
        this.txtFacturado.setEnabled(value);
        this.txtPOS1.setEnabled(value);
        this.txtPOS2.setEnabled(value);
        this.txtMontoJustificacion.setEnabled(value);
        this.txtJustificacion.setEnabled(value);
        this.txtDeposito.setEnabled(value);
        this.btnAceptar.setEnabled(value);
    }

    private void cajaFinal() {
        double deposito = Double.parseDouble((this.txtDeposito.getTextoSinFormato().length() <= 0 ? "0" : this.txtDeposito.getTextoSinFormato()));

        this.lblCajaFinal.setText("Lps " + df2.format(montoTotalCaja - deposito));
        cajaFinal = montoTotalCaja - deposito;
    }

    private void diferencia() {
        double pos1 = Double.parseDouble((this.txtPOS1.getTextoSinFormato().length() <= 0 ? "0" : this.txtPOS1.getTextoSinFormato()));
        double pos2 = Double.parseDouble((this.txtPOS2.getTextoSinFormato().length() <= 0 ? "0" : this.txtPOS2.getTextoSinFormato()));

        double diferencia = (cajaApertura + pos1 + pos2) - facturado;

        this.txtDiferencia.setText(df2.format(diferencia));
    }

    private void guardar() throws ParseException, SQLException, IllegalArgumentException, IllegalAccessException {

        CierreDiario dto = new CierreDiario();

        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date parsed = format.parse(this.lblFechaCierre.getText());
        java.sql.Date sqlDate = new java.sql.Date(parsed.getTime());

        dto.setSecuencia(CodigoSecuencia);
        dto.setFechaCierre(sqlDate);
        dto.setCajaInicio(cajaInicial);
        dto.setCantidad500(Integer.parseInt((this.txtCantidad500.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad500.getTextoSinFormato())));
        dto.setCantidad100(Integer.parseInt((this.txtCantidad100.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad100.getTextoSinFormato())));
        dto.setCantidad50(Integer.parseInt((this.txtCantidad50.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad50.getTextoSinFormato())));
        dto.setCantidad20(Integer.parseInt((this.txtCantidad20.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad20.getTextoSinFormato())));
        dto.setCantidad10(Integer.parseInt((this.txtCantidad10.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad10.getTextoSinFormato())));
        dto.setCantidad5(Integer.parseInt((this.txtCantidad5.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad5.getTextoSinFormato())));
        dto.setCantidad2(Integer.parseInt((this.txtCantidad2.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad2.getTextoSinFormato())));
        dto.setCantidad1(Integer.parseInt((this.txtCantidad1.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad1.getTextoSinFormato())));
        dto.setMontoMoneda(Double.parseDouble((this.txtMontoMonedas.getTextoSinFormato().length() <= 0 ? "0" : this.txtMontoMonedas.getTextoSinFormato())));
        dto.setMontoFacturado(facturado);
        dto.setMontoPOS1(Double.parseDouble((this.txtPOS1.getTextoSinFormato().length() <= 0 ? "0" : this.txtPOS1.getTextoSinFormato())));
        dto.setMontoPOS2(Double.parseDouble((this.txtPOS2.getTextoSinFormato().length() <= 0 ? "0" : this.txtPOS2.getTextoSinFormato())));
        dto.setMontoJustificacion(Double.parseDouble((this.txtMontoJustificacion.getTextoSinFormato().length() <= 0 ? "0" : this.txtMontoJustificacion.getTextoSinFormato())));
        dto.setJustificacion(this.txtJustificacion.getText());
        dto.setMontoDeposito(Double.parseDouble((this.txtDeposito.getTextoSinFormato().length() <= 0 ? "0" : this.txtDeposito.getTextoSinFormato())));
        dto.setCajaFinal(cajaFinal);
        dto.setStrFacturado(this.txtFacturado.getTextoSinFormato());

        boolean retValue;
        retValue = CierreDiarioBC.editar(CnnMySql.getAccion(), dto);

        CnnMySql.setAccion(CnnMySql.ACCION_UPDATE);
    }

    private void totalCaja() {
        double c500 = 500 * Double.parseDouble((this.txtCantidad500.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad500.getTextoSinFormato()));
        double c100 = 100 * Double.parseDouble((this.txtCantidad100.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad100.getTextoSinFormato()));
        double c50 = 50 * Double.parseDouble((this.txtCantidad50.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad50.getTextoSinFormato()));
        double c20 = 20 * Double.parseDouble((this.txtCantidad20.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad20.getTextoSinFormato()));
        double c10 = 10 * Double.parseDouble((this.txtCantidad10.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad10.getTextoSinFormato()));
        double c5 = 5 * Double.parseDouble((this.txtCantidad5.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad5.getTextoSinFormato()));
        double c2 = 2 * Double.parseDouble((this.txtCantidad2.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad2.getTextoSinFormato()));
        double c1 = 1 * Double.parseDouble((this.txtCantidad1.getTextoSinFormato().length() <= 0 ? "0" : this.txtCantidad1.getTextoSinFormato()));
        double coins = Double.parseDouble((this.txtMontoMonedas.getTextoSinFormato().length() <= 0 ? "0" : this.txtMontoMonedas.getTextoSinFormato()));

        montoTotalCaja = (c500 + c100 + c50 + c20 + c10 + c5 + c2 + c1 + coins);
        this.lblMontoTotalCaja.setText("= Lps " + df2.format(c500 + c100 + c50 + c20 + c10 + c5 + c2 + c1 + coins));
        cajaApertura = (c500 + c100 + c50 + c20 + c10 + c5 + c2 + c1 + coins) - cajaInicial;
        this.lblCajaApertura.setText("Lps " + df2.format((c500 + c100 + c50 + c20 + c10 + c5 + c2 + c1 + coins) - cajaInicial));
    }

    private void ObtenerCierre(String fecha) {

        try {

            cajaInicial = CierreDiarioBC.getCajaInicial(fecha);

            if (cajaInicial <= 0.0) {                
                String respuesta = JOptionPane.showInputDialog(this, "Ingrese Caja Inicial", "Cierre Diario", JOptionPane.QUESTION_MESSAGE);
                cajaInicial = Double.valueOf(respuesta);
            }
            this.lblCajaInicial.setText("Lps " + df2.format(cajaInicial));

            CierreDiario dto;
            dto = CierreDiarioBC.getCierreDiario(fecha);

            if (dto != null) {

                CodigoSecuencia = dto.getSecuencia();
                this.txtCantidad500.setText(String.valueOf(dto.getCantidad500()));
                this.lblMonto500.setText("= Lps " + df2.format((500 * dto.getCantidad500())));

                this.txtCantidad100.setText(String.valueOf(dto.getCantidad100()));
                this.lblMonto100.setText("= Lps " + df2.format((100 * dto.getCantidad100())));

                this.txtCantidad50.setText(String.valueOf(dto.getCantidad50()));
                this.lblMonto50.setText("= Lps " + df2.format((50 * dto.getCantidad50())));

                this.txtCantidad20.setText(String.valueOf(dto.getCantidad20()));
                this.lblMonto20.setText("= Lps " + df2.format((20 * dto.getCantidad20())));

                this.txtCantidad10.setText(String.valueOf(dto.getCantidad10()));
                this.lblMonto10.setText("= Lps " + df2.format((10 * dto.getCantidad10())));

                this.txtCantidad5.setText(String.valueOf(dto.getCantidad5()));
                this.lblMonto5.setText("= Lps " + df2.format((5 * dto.getCantidad5())));

                this.txtCantidad2.setText(String.valueOf(dto.getCantidad2()));
                this.lblMonto2.setText("= Lps " + df2.format((2 * dto.getCantidad2())));

                this.txtCantidad1.setText(String.valueOf(dto.getCantidad1()));
                this.lblMonto1.setText("= Lps " + df2.format((1 * dto.getCantidad1())));

                this.txtMontoMonedas.setText(String.valueOf(df2.format(dto.getMontoMoneda())));

                this.txtFacturado.setText(dto.getStrFacturado());
                this.lblFacturado.setText("Lps " + String.valueOf(df2.format(dto.getMontoFacturado())));

                this.txtPOS1.setText(String.valueOf(df2.format(dto.getMontoPOS1())));
                this.txtPOS2.setText(String.valueOf(df2.format(dto.getMontoPOS2())));
                this.txtMontoJustificacion.setText(String.valueOf(df2.format(dto.getMontoJustificacion())));
                this.txtJustificacion.setText(dto.getJustificacion());
                this.txtDeposito.setText(String.valueOf(df2.format(dto.getMontoDeposito())));

                totalCaja();
                calcularFacturado();
                diferencia();
                cajaFinal();

                CnnMySql.setAccion(CnnMySql.ACCION_UPDATE);
            }

        } catch (SQLException | IllegalArgumentException | IllegalAccessException ex) {
            Logger.getLogger(RegistraCierreDiario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private final DecimalFormat df2 = new DecimalFormat("#,###,###,##0.00");
    private Double cajaApertura = 0.0;
    private Double cajaInicial = 0.0;
    private Double cajaFinal = 0.0;
    private Double facturado = 0.0;
    private Double montoTotalCaja = 0.0;
    private Integer CodigoSecuencia = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gmail.lrchfox3.controles.botones.JBotonAceptar btnAceptar;
    private com.gmail.lrchfox3.controles.botones.paint.JBotonLapiz btnEditarFechaCierre;
    private com.gmail.lrchfox3.utilitarios.calendario.JDateChooser dtFechaCierre;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo1;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo2;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo3;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.gmail.lrchfox3.controles.textos.JTextoScrollBase jTextoScrollBase1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl10;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl100;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl20;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl5;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl50;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl500;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl505;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblApertura;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblApertura1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblAperturaAnterior;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCaja;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblCajaApertura;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblCajaFinal;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblCajaInicial;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCantidadBilletes;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCantidadBilletes3;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCantidadBilletes4;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCantidadBilletes5;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato lblDepositoAnterior;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblDiferencia;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato lblDiferenciaAnterior;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblFacturado;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblFacturadoAnterior;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblFecha;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblFechaCierre;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblJustificacion;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonedas;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto10;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto100;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto20;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto5;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto50;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto500;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblMontoTotalCaja;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblPOS1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblPOS2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblTotalCaja;
    private javax.swing.JMenuItem mnuLimpiar;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo pnlCaja;
    private javax.swing.JPopupMenu popCaja;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad1;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad10;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad100;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad2;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad20;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad5;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad50;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad500;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtDeposito;
    private com.gmail.lrchfox3.controles.textos.JTextoBase txtDiferencia;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtFacturado;
    private javax.swing.JTextPane txtJustificacion;
    private com.gmail.lrchfox3.controles.textos.JComentarioBase txtJustificacionAnterior;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtMontoJustificacion;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtMontoMonedas;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtPOS1;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtPOS2;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtPOS4;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtPOS5;
    // End of variables declaration//GEN-END:variables
}
